### ISSUE TITLE
Create a new layout and add Jupyter notebooks describing functionality

### ISSUE THREAD

**Issue by raumannsr** [tueimage/crowd-multitask#8]
The issue is done when at least: 1. all parts have the new layout, 2. for each part a Jupyter notebook with documentation is present, and 3. the code able to produce the results described in Elif’s report

**Comment by reubenvarghese1** [comment]
Here's the pr for this issue: https://github.com/tueimage/crowd-multitask/pull/9 . I'll be updating it over the next few days as it still needs some work. Thanks!
